train: true
model_name: "yolo12n"

project_name: "EyeInTheSky"
dataset_name: "VisDrone"

raw_data_dir: "data/raw"
data_dir: "data"
config_dir: "config"
interim_data_dir: "data/interim"
processed_data_dir: "data/processed"
external_data_dir: "data/external"
models_dir: "models"
reports_dir: "reports"
figures_dir: "reports/figures"

# Ray Tune Configuration
shared_args:
  workers: 8               # Number of data loader workers
  seed: 42                 # Random seed
  exist_ok: False          # Don't increment run if exists
  cos_lr: True            # Cosine learning rate
  imgsz: 640               # Input image size

# Fixed Training Configuration
train:
  experiment_name: "YOLO_VisDrone-Training"
  epochs: 300             # Number of training epochs
  plots: True             # Don't create training plots during tuning
  save: True              # Save checkpoints
  save_period: 10         # Save every X epochs
  val: True               # Run validation

tune:
  train_args:
    experiment_name: 'YOLO_VisDrone-Tuning' # Experiment name
    iterations: 30
    grace_period: 10 
    plots: False
    val: False
    patience: 10            # Early stopping patience
    overlap_mask: True      # Overlapping masks
    mask_ratio: 4           # Mask downsample ratio
  space:
    lr0: {"min": 1e-5, "max": 1e-1}
    lrf: {"min": 0.01, "max": 1.0}
    momentum: {"min": 0.6, "max": 0.98}
    weight_decay: {"min": 0.0, "max": 0.001}
    warmup_momentum: {"min": 0.0, "max": 0.95}
    cls: {"min": 0.2, "max": 4.0}
    hsv_h: {"min": 0.0, "max": 0.1}
    hsv_s: {"min": 0.0, "max": 0.9}
    hsv_v: {"min": 0.0, "max": 0.9}